In [6]:
import numpy as np

A=np.array([10,20,30,40,50])
B=np.array([1,2,3,4,5])
add=np.add(A,B)
print(add)
sub=np.subtract(A,B)
print(sub)
mul=np.multiply(A,B)
print(mul)
div=np.divide(A,B)
print(div)

mean_A=np.mean(A)
print(mean_A)
max_A=np.max(A)
print(max_A)
min_A=np.min(A)
print(min_A)
dot_AB=np.dot(A,B)
print(dot_AB)

reshaped_A=np.reshape(A,(5,1))
print(reshaped_A)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
30.0
50
10
550
[[10]
 [20]
 [30]
 [40]
 [50]]

In [14]:
import pandas as pd

students_data=pd.DataFrame({"Name": ['tito','youssef','omar','mahmoud','ali']
,"Age":[20,15,25,30,19]
,"Grade":['A','D','B','A','C']
,"Marks":[90,70,88,65,60] })
print(students_data)
print(students_data.head(3))
print(students_data[["Name","Marks"]])
print(students_data[students_data["Grade"]=="A"])

      Name  Age Grade  Marks
0     tito   20     A     90
1  youssef   15     D     70
2     omar   25     B     88
3  mahmoud   30     A     65
4      ali   19     C     60
      Name  Age Grade  Marks
0     tito   20     A     90
1  youssef   15     D     70
2     omar   25     B     88
      Name  Marks
0     tito     90
1  youssef     70
2     omar     88
3  mahmoud     65
4      ali     60
      Name  Age Grade  Marks
0     tito   20     A     90
3  mahmoud   30     A     65